# Generated by Django 5.1.4 on 2024-12-24 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lession6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='lession1')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('lession1', '1'), ('lession2', '2'), ('lession3', '3'), ('lession4', '4')], max_length=10)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
