# Generated by Django 5.1.4 on 2024-12-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lession7_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessions',
            name='description',
            field=models.TextField(default='No description available', max_length=250),
        ),
        migrations.AlterField(
            model_name='lessions',
            name='type',
            field=models.CharField(choices=[('lesson1', '1'), ('lesson2', '2'), ('lesson3', '3'), ('lesson4', '4')], max_length=100),
        ),
    ]
