# Generated by Django 5.1.4 on 2024-12-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lession5_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessions',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
